baseURL = "https://salauer.github.io/"
title = "Stephen A. Lauer"
theme = "academic"

# Get last modified date for content from Git?
enableGitInfo = false

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false
removePathAccents = true  # Workaround for https://github.com/gohugoio/hugo/issues/5687

paginate = 10  # Number of items per page in paginated lists.
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[outputs]
  home = [ "HTML", "RSS", "JSON", "WebAppManifest" ]
  section = [ "HTML", "RSS" ]

[mediaTypes."application/manifest+json"]
  suffixes = ["webmanifest"]

[outputFormats.WebAppManifest]
  mediaType = "application/manifest+json"
  rel = "manifest"

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab. See https://github.com/gohugoio/hugo/issues/2424
	angledQuotes = false
	latexDashes = true
  extensions = ["backslashLineBreak"]

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"


[permalinks]
  post = "/:year/:month/:day/:slug"

#[params]
#  avatar = "profile.jpg"
#  author = "Stephen A. Lauer"
#  description = "I'm Steve Lauer, a biostatistician."

#  # Custom assets can be linked with their paths relative to static/
#  custom_css = []
#  custom_js  = []

#[params.social]
#  Email         = "slauer5@jh.edu"
#  Github        = "salauer"
#  Scholar       = "citations?user=EEKbG5sAAAAJ&hl=en"

# [params.vitae]
#  website = "git.io/sustain"
#  website_full = "https://demo.nurlan.co/hugo-sustain/"
#  city = "Baltimore, MD"
#  country = "USA"

## Main Menu
#[[menu.main]]
#  name = "blog"
#  weight = 100
#  identifier = "blog"
#  url = "/blog/"
#[[menu.main]]
#  name = "resume"
#  identifier = "resume"
#  weight = 200
#  url = "/vitae/"
